### ISSUE TITLE
how to using DevExpress.Xpf.Grid

### ISSUE THREAD

**Issue by edsonfast** [DevExpress-Examples/how-to-load-data-in-an-unbound-column-asynchronously-e3140#1]
https://github.com/DevExpress-Examples/how-to-load-data-in-an-unbound-column-asynchronously-e3140/blob/91c2126ecaf6553e72654641e9b900ddf143f62c/CS/WindowsApplication3/Main.cs#L73

**Comment by AlexGreenZ** [comment]
Hello,

As I can see, you have already asked a similar question in the context of the https://supportcenter.devexpress.com/ticket/details/t946917/wpf-grid-how-to-asynchronously-load-data-in-an-unbound-column-located-in-gridcontrol thread. Let's continue our discussion there.
